<?php

namespace Database\Seeders;

use App\Models\VariableCities;
use Illuminate\Database\Seeder;

class VariabelCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities =
            [
                "Kota Banda Aceh",
                "Kota Sabang",
                "Kota Lhokseumawe",
                "Kota Langsa",
                "Kota Subulussalam",
                "Kabupaten Aceh Selatan",
                "Kabupaten Aceh Tenggara",
                "Kabupaten Aceh Timur",
                "Kabupaten Aceh Tengah",
                "Kabupaten Aceh Barat",
                "Kabupaten Aceh Besar",
                "Kabupaten Pidie",
                "Kabupaten Aceh Utara",
                "Kabupaten Simeulue",
                "Kabupaten Aceh Singkil",
                "Kabupaten Bireun",
                "Kabupaten Aceh Barat Daya",
                "Kabupaten Gayo Lues",
                "Kabupaten Aceh Jaya",
                "Kabupaten Nagan Raya",
                "Kabupaten Aceh Tamiang",
                "Kabupaten Bener Meriah",
                "Kabupaten Pidie Jaya",
                "Kota Medan",
                "Kota Pematang Siantar",
                "Kota Sibolga",
                "Kota Tanjung Balai",
                "Kota Binjai",
                "Kota Tebing Tinggi",
                "Kota Padang Sidempuan",
                "Kota Gunung Sitoli",
                "Kabupaten Serdang Bedagai",
                "Kabupaten Samosir ",
                "Kabupaten Humbang Hasundutan",
                "Kabupaten Pakpak Bharat",
                "Kabupaten Nias Selatan",
                "Kabupaten Mandailing Natal",
                "Kabupaten Toba Samosir",
                "Kabupaten Dairi",
                "Kabupaten Labuhan Batu",
                "Kabupaten Asahan",
                "Kabupaten Simalungun",
                "Kabupaten Deli Serdang",
                "Kabupaten Karo",
                "Kabupaten Langkat",
                "Kabupaten Nias",
                "Kabupaten Tapanuli Selatan",
                "Kabupaten Tapanuli Utara",
                "Kabupaten Tapanuli Tengah",
                "Kabupaten Batu Bara",
                "Kabupaten Padang Lawas Utara",
                "Kabupaten Padang Lawas",
                "Kabupaten Labuhanbatu Selatan",
                "Kabupaten Labuhanbatu Utara",
                "Kabupaten Nias Utara",
                "Kabupaten Nias Barat",
                "Kota Padang",
                "Kota Solok",
                "Kota Sawhlunto",
                "Kota Padang Panjang",
                "Kota Bukittinggi",
                "Kota Payakumbuh",
                "Kota Pariaman",
                "Kabupaten Pasaman Barat",
                "Kabupaten Solok Selatan",
                "Kabupaten Dharmasraya",
                "Kabupaten Kepulauan Mentawai",
                "Kabupaten Pasaman",
                "Kabupaten Lima Puluh Kota",
                "Kabupaten Agam",
                "Kabupaten Padang Pariaman",
                "Kabupaten Tanah Datar",
                "Kabupaten Sijunjung",
                "Kabupaten Solok",
                "Kabupaten Pesisir Selatan",
                "Kota Pekan Baru",
                "Kota Dumai",
                "Kabupaten Kepulauan Meranti",
                "Kabupaten Kuantan Singingi",
                "Kabupaten Siak",
                "Kabupaten Rokan Hilir",
                "Kabupaten Rokan Hulu",
                "Kabupaten Pelalawan",
                "Kabupaten Indragiri Hilir",
                "Kabupaten Bengkalis",
                "Kabupaten Indragiri Hulu",
                "Kabupaten Kampar",
                "Kota Jambi",
                "Kota Sungai Penuh",
                "Kabupaten Tebo",
                "Kabupaten Bungo",
                "Kabupaten Tanjung Jabung Timur",
                "Kabupaten Tanjung Jabung Barat",
                "Kabupaten Muaro Jambi",
                "Kabupaten Batanghari",
                "Kabupaten Sarolangun",
                "Kabupaten Merangin",
                "Kabupaten Kerinci",
                "Kota Palembang",
                "Kota Pagar Alam",
                "Kota Lubuk Linggau",
                "Kota Prabumulih",
                "Kabupaten Musi Rawas Utara",
                "Kabupaten Penukal Abab Lematang Ilir",
                "Kabupaten Empat Lawang",
                "Kabupaten Ogan Ilir ",
                "Kabupaten Ogan Komering Ulu Selatan ",
                "Kabupaten Ogan Komering Ulu Timur ",
                "Kabupaten Banyuasin",
                "Kabupaten Musi Banyuasin",
                "Kabupaten Musi Rawas",
                "Kabupaten Lahat",
                "Kabupaten Muara Enim",
                "Kabupaten Ogan Komering Ilir",
                "Kabupaten Ogan Komering Ulu",
                "Kota Bengkulu",
                "Kabupaten Bengkulu Tengah",
                "Kabupaten Kepahiang ",
                "Kabupaten Lebong",
                "Kabupaten Muko Muko",
                "Kabupaten Seluma",
                "Kabupaten Kaur",
                "Kabupaten Bengkulu Utara",
                "Kabupaten Rejang Lebong",
                "Kabupaten Bengkulu Selatan",
                "Kota Bandar Lampung",
                "Kota Metro",
                "Kabupaten Pesisir Barat",
                "Kabupaten Tulangbawang Barat",
                "Kabupaten Mesuji",
                "Kabupaten Pringsewu",
                "Kabupaten Pesawaran",
                "Kabupaten Way Kanan",
                "Kabupaten Lampung Timur",
                "Kabupaten Tanggamus",
                "Kabupaten Tulang Bawang",
                "Kabupaten Lampung Barat",
                "Kabupaten Lampung Utara",
                "Kabupaten Lampung Tengah",
                "Kabupaten Lampung Selatan",
                "Kota Pangkal Pinang",
                "Kabupaten Belitung Timur",
                "Kabupaten Bangka Barat",
                "Kabupaten Bangka Tengah",
                "Kabupaten Bangka Selatan",
                "Kabupaten Belitung",
                "Kabupaten Bangka",
                "Kota Batam",
                "Kota Tanjung Pinang",
                "Kabupaten Kepulauan Anambas",
                "Kabupaten Lingga ",
                "Kabupaten Natuna",
                "Kabupaten Karimun",
                "Kabupaten Bintan",
                "Kota Jakarta Timur",
                "Kota Jakarta Selatan",
                "Kota Jakarta Barat",
                "Kota Jakarta Utara",
                "Kota Jakarta Pusat",
                "Kabupaten Kepulauan Seribu",
                "Kota Bandung",
                "Kota Banjar",
                "Kota Tasikmalaya",
                "Kota Cimahi",
                "Kota Depok",
                "Kota Bekasi",
                "Kota Cirebon",
                "Kota Sukabumi",
                "Kota Bogor",
                "Kabupaten Pangandaran",
                "Kabupaten Bandung Barat",
                "Kabupaten Bekasi",
                "Kabupaten Karawang",
                "Kabupaten Purwakarta",
                "Kabupaten Subang",
                "Kabupaten Indramayu",
                "Kabupaten Sumedang",
                "Kabupaten Majalengka",
                "Kabupaten Cirebon",
                "Kabupaten Kuningan",
                "Kabupaten Ciamis",
                "Kabupaten Tasikmalaya",
                "Kabupaten Garut",
                "Kabupaten Bandung",
                "Kabupaten Cianjur",
                "Kabupaten Sukabumi",
                "Kabupaten Bogor",
                "Kota Semarang",
                "Kota Tegal",
                "Kota Pekalongan",
                "Kota Salatiga",
                "Kota Surakarta",
                "Kota Magelang",
                "Kabupaten Brebes",
                "Kabupaten Tegal",
                "Kabupaten Pemalang",
                "Kabupaten Pekalongan",
                "Kabupaten Batang",
                "Kabupaten Kendal",
                "Kabupaten Temanggung",
                "Kabupaten Semarang",
                "Kabupaten Demak",
                "Kabupaten Jepara",
                "Kabupaten Kudus",
                "Kabupaten Pati",
                "Kabupaten Rembang",
                "Kabupaten Blora",
                "Kabupaten Grobogan",
                "Kabupaten Sragen",
                "Kabupaten Karanganyar",
                "Kabupaten Wonogiri",
                "Kabupaten Sukoharjo",
                "Kabupaten Klaten",
                "Kabupaten Boyolali",
                "Kabupaten Magelang",
                "Kabupaten Wonosobo",
                "Kabupaten Purworejo",
                "Kabupaten Kebumen",
                "Kabupaten Banjarnegara",
                "Kabupaten Purbalingga",
                "Kabupaten Banyumas",
                "Kabupaten Cilacap",
                "Kota Yogyakarta",
                "Kabupaten Sleman",
                "Kabupaten Gunung Kidul",
                "Kabupaten Bantul",
                "Kabupaten Kulon Progo",
                "Kota Surabaya",
                "Kota Batu",
                "Kota Madiun",
                "Kota Mojokerto",
                "Kota Pasuruan",
                "Kota Probolinggo",
                "Kota Malang",
                "Kota Blitar",
                "Kota Kediri",
                "Kabupaten Sumenep",
                "Kabupaten Pamekasan",
                "Kabupaten Sampang",
                "Kabupaten Bangkalan",
                "Kabupaten Gresik",
                "Kabupaten Lamongan",
                "Kabupaten Tuban",
                "Kabupaten Bojonegoro",
                "Kabupaten Ngawi",
                "Kabupaten Magetan",
                "Kabupaten Madiun",
                "Kabupaten Nganjuk",
                "Kabupaten Jombang",
                "Kabupaten Mojokerto",
                "Kabupaten Sidoarjo",
                "Kabupaten Pasuruan",
                "Kabupaten Probolinggo",
                "Kabupaten Situbondo",
                "Kabupaten Bondowoso",
                "Kabupaten Banyuwangi",
                "Kabupaten Jember",
                "Kabupaten Lumajang",
                "Kabupaten Malang",
                "Kabupaten Kediri",
                "Kabupaten Blitar",
                "Kabupaten Tulungagung",
                "Kabupaten Trenggalek",
                "Kabupaten Ponorogo",
                "Kabupaten Pacitan",
                "Kota Serang",
                "Kota Cilegon",
                "Kota Tangerang",
                "Kota Tangerang Selatan",
                "Kabupaten Serang",
                "Kabupaten Tangerang",
                "Kabupaten Lebak",
                "Kabupaten Pandeglang",
                "Kota Denpasar",
                "Kabupaten Buleleng",
                "Kabupaten Karangasem",
                "Kabupaten Bangli",
                "Kabupaten Klungkung",
                "Kabupaten Gianyar",
                "Kabupaten Badung",
                "Kabupaten Tabanan",
                "Kabupaten Jembrana",
                "Kota Mataram",
                "Kota Bima",
                "Kabupaten Lombok Utara",
                "Kabupaten Sumbawa Barat",
                "Kabupaten Bima",
                "Kabupaten Dompu",
                "Kabupaten Sumbawa ",
                "Kabupaten Lombok Timur",
                "Kabupaten Lombok Tengah",
                "Kabupaten Lombok Barat",
                "Kota Kupang",
                "Kabupaten Malaka",
                "Kabupaten Sabu Raijua",
                "Kabupaten Manggarai Timur",
                "Kabupaten Sumba Barat Daya",
                "Kabupaten Sumba Tengah",
                "Kabupaten Nagekeo",
                "Kabupaten Manggarai Barat",
                "Kabupaten Rote Ndao",
                "Kabupaten Lembata",
                "Kabupaten Sumba Barat",
                "Kabupaten Sumba Timur",
                "Kabupaten Manggarai",
                "Kabupaten Ngada",
                "Kabupaten Ende",
                "Kabupaten Sikka",
                "Kabupaten Flores Timur",
                "Kabupaten Alor",
                "Kabupaten Belu",
                "Kabupaten Timor Tengah Utara",
                "Kabupaten Timor Tengah Selatan",
                "Kabupaten Kupang",
                "Kota Pontianak",
                "Kota Singkawang",
                "Kabupaten Kubu Raya",
                "Kabupaten Kayong Utara",
                "Kabupaten Sekadau",
                "Kabupaten Melawi",
                "Kabupaten Landak",
                "Kabupaten Bengkayang",
                "Kabupaten Kapuas Hulu",
                "Kabupaten Sintang ",
                "Kabupaten Ketapang",
                "Kabupaten Sanggau ",
                "Kabupaten Mempawah",
                "Kabupaten Sambas",
                "Kota Palangkaraya",
                "Kabupaten Barito Timur",
                "Kabupaten Murung Raya",
                "Kabupaten Pulang Pisau",
                "Kabupaten Gunung Mas",
                "Kabupaten Lamandau",
                "Kabupaten Sukamara",
                "Kabupaten Seruyan",
                "Kabupaten Katingan",
                "Kabupaten Barito Utara",
                "Kabupaten Barito Selatan",
                "Kabupaten Kapuas",
                "Kabupaten Kotawaringin Timur",
                "Kabupaten Kotawaringin Barat",
                "Kota Banjarmasin",
                "Kota Banjarbaru",
                "Kabupaten Balangan",
                "Kabupaten Tanah Bambu",
                "Kabupaten Tabalong",
                "Kabupaten Hulu Sungai Utara",
                "Kabupaten Hulu Sungai Tengah",
                "Kabupaten Hulu Sungai Selatan",
                "Kabupaten Tapin",
                "Kabupaten Barito Kuala",
                "Kabupaten Banjar",
                "Kabupaten Kotabaru",
                "Kabupaten Tanah Laut",
                "Kota Samarinda",
                "Kota Bontang",
                "Kota Balikpapan",
                "Kabupaten Mahakam Ulu",
                "Kabupaten Penajam Paser Utara",
                "Kabupaten Kutai Timur",
                "Kabupaten Kutai Barat",
                "Kabupaten Berau",
                "Kabupaten Kutai Kertanegara",
                "Kabupaten Paser",
                "Kota Tarakan",
                "Kabupaten Tana Tidung",
                "Kabupaten Nunukan",
                "Kabupaten Malinau",
                "Kabupaten Bulungan",
                "Kota Manado",
                "Kota Tomohon",
                "Kota Bitung",
                "Kota Kotamobagu",
                "Kabupaten Bolaang Mangondow Selatan",
                "Kabupaten Bolaang Mangondow Timur",
                "Kabupaten Kepulauan Siau Tagulandang Biaro",
                "Kabupaten Bolaang Mangondow Utara",
                "Kabupaten Minahasa Tenggara",
                "Kabupaten Minahasa Utara",
                "Kabupaten Minahasa Selatan",
                "Kabupaten Kepulauan Talaud",
                "Kabupaten Kepulauan Sangihe",
                "Kabupaten Minahasa",
                "Kabupaten Bolaang Mangondow",
                "Kota Palu",
                "Kabupaten Morowali Utara",
                "Kabupaten Banggai Laut",
                "Kabupaten Sigi",
                "Kabupaten Tojo Una-Una",
                "Kabupaten Parigi Moutong",
                "Kabupaten Banggai Kepulauan",
                "Kabupaten Morowali",
                "Kabupaten Buol",
                "Kabupaten Toli-Toli",
                "Kabupaten Donggala",
                "Kabupaten Poso",
                "Kabupaten Banggai",
                "Kota Makasar",
                "Kota Palopo",
                "Kota Pare Pare",
                "Kabupaten Toraja Utara",
                "Kabupaten Luwu Timur",
                "Kabupaten Luwu Utara",
                "Kabupaten Tana Toraja",
                "Kabupaten Luwu",
                "Kabupaten Enrekang",
                "Kabupaten Pinrang",
                "Kabupaten Sidenreng Rappang",
                "Kabupaten Wajo",
                "Kabupaten Soppeng",
                "Kabupaten Barru",
                "Kabupaten Pangkajene Kepulauan",
                "Kabupaten Maros",
                "Kabupaten Bone",
                "Kabupaten Sinjai",
                "Kabupaten Gowa",
                "Kabupaten Takalar",
                "Kabupaten Jeneponto",
                "Kabupaten Bantaeng",
                "Kabupaten Bulukumba",
                "Kabupaten Kepulauan Selayar",
                "Kota Kendari",
                "Kota Bau Bau",
                "Kabupaten Buton Selatan",
                "Kabupaten Buton Tengah",
                "Kabupaten Muna Barat",
                "Kabupaten Konawe Kepulauan",
                "Kabupaten Kolaka Timur",
                "Kabupaten Buton Utara",
                "Kabupaten Konawe Utara",
                "Kabupaten Kolaka Utara",
                "Kabupaten Wakatobi",
                "Kabupaten Bombana",
                "Kabupaten Konawe Selatan",
                "Kabupaten Buton",
                "Kabupaten Muna",
                "Kabupaten Konawe",
                "Kabupaten Kolaka",
                "Kota Gorontalo",
                "Kabupaten Pohuwato",
                "Kabupaten Bone Bolango",
                "Kabupaten Boalemo",
                "Kabupaten Gorontalo",
                "Kabupaten Gorontalo Utara",
                "Kabupaten Majene",
                "Kabupaten Polowali Mandar",
                "Kabupaten Mamasa",
                "Kabupaten Mamuju",
                "Kabupaten Mamuju Utara",
                "Kabupaten Mamuju Tengah",
                "Kota Ambon",
                "Kota Tual",
                "Kabupaten Buru Selatan",
                "Kabupaten Maluku Barat Daya",
                "Kabupaten Kepulauan Aru",
                "Kabupaten Seram Bagian Barat ",
                "Kabupaten Seram Bagian Timur",
                "Kabupaten Buru",
                "Kabupaten Maluku Tenggara Barat",
                "Kabupaten Maluku Tenggara",
                "Kabupaten Maluku Tengah",
                "Kota Ternate",
                "Kota Tidore Kepulauan",
                "Kabupaten Pulau Taliabu",
                "Kabupaten Pulau Morotai",
                "Kabupaten Halmahera Timur",
                "Kabupaten Kepulauan Sula",
                "Kabupaten Halmahera Selatan",
                "Kabupaten Halmahera Utara",
                "Kabupaten Halmahera Tengah",
                "Kabupaten Halmahera Barat",
                "Kota Jayapura",
                "Kabupaten Deiyai",
                "Kabupaten Intan Jaya",
                "Kabupaten Dogiyai",
                "Kabupaten Puncak",
                "Kabupaten Nduga",
                "Kabupaten Lanny Jaya",
                "Kabupaten Yalimo",
                "Kabupaten Mamberamo Tengah",
                "Kabupaten Mamberamo Raya",
                "Kabupaten Supiori",
                "Kabupaten Asmat",
                "Kabupaten Mappi",
                "Kabupaten Boven Digoel",
                "Kabupaten Waropen",
                "Kabupaten Tolikara",
                "Kabupaten Yahukimo",
                "Kabupaten Pegunungan Bintang",
                "Kabupaten Keerom",
                "Kabupaten Sarmi",
                "Kabupaten Mimika",
                "Kabupaten Paniai",
                "Kabupaten Puncak Jaya",
                "Kabupaten Biak Numfor",
                "Kabupaten Kepulauan Yapen",
                "Kabupaten Nabire",
                "Kabupaten Jayapura",
                "Kabupaten Jayawijaya",
                "Kabupaten Merauke",
                "Kota Sorong",
                "Kabupaten Pegunungan Arfak",
                "Kabupaten Manokwari Selatan",
                "Kabupaten Maybrat",
                "Kabupaten Tambrauw",
                "Kabupaten Kaimana",
                "Kabupaten Teluk Wondama",
                "Kabupaten Teluk Bintuni",
                "Kabupaten Raja Ampat",
                "Kabupaten Sorong Selatan",
                "Kabupaten Fak Fak",
                "Kabupaten Manokwari",
                "Kabupaten Sorong"
            ];


        $i = 1;
        foreach ($cities as $city) {
            $city_code = $i <= 5 ? 'CITY-000' . $i : generateFiledCode('CITY');

            VariableCities::create([
                'city_code' => $city_code,
                'city_name' => $city
            ]);
            $i++;
        }

    }
}
